# Server URL
publicUrl: http://localhost:8080/

# Password iterations (See https://security.stackexchange.com/questions/3959/recommended-of-iterations-when-using-pkbdf2-sha256)
passwordIterations: 25000

# Password cache
passwordCache: maximumSize=10000,expireAfterWrite=20m

# Number of galaxies
galaxies: 10

# Number of solar systems in a galaxy
solarSystems: 10

# Number of planets in a solar system
planets: 10

# Round time in seconds
roundTime: 1

# Calculate points every X rounds
calculatePointsEvery: 10

# Debug options
debug:
    # If true all flights take 1 round to reach destination
    speedUpFlights: false
    # If true all researches take 1 round to complete
    speedUpResearches: false
    # If true all buildings take 1 round to complete
    speedUpBuildingConstructions: false
    # If true all ships take 1 round to complete
    speedUpShipConstructions: false
    # If true, all ships are for free
    freeShips: false
    # If true, all researches are for free
    freeResearches: false
    # If true, all buildings are for free
    freeBuildings: false
    # If true, all flights are for free
    freeFlights: false
    # If true, buildings have no prerequisites
    noBuildingPrerequisites: false
    # If true, ships have no prerequisites
    noShipPrerequisites: false
    # If true, researches have no prerequisites
    noResearchPrerequisites: false

# Database configuration
database:
    driverClass: org.h2.Driver
    url: jdbc:h2:/tmp/restwars
    user:
    password:

# Logging configuration
logging:
    level: WARN
    loggers:
        "io.dropwizard.jersey.DropwizardResourceConfig": INFO
        "restwars": TRACE
    appenders:
      - type: console
        threshold: ALL
        timeZone: UTC
      - type: file
        currentLogFilename: /tmp/restwars-error.log
        threshold: ERROR
        archive: true
        archivedLogFilenamePattern: /tmp/restwars-error-%d.log
        archivedFileCount: 5
        timeZone: UTC