serverName: localhost
database:
    driverClass: org.h2.Driver
    url: jdbc:h2:/tmp/restwars
    user:
    password:
logging:
    level: WARN
    loggers:
        "io.dropwizard.jersey.DropwizardResourceConfig": INFO
        "restwars": TRACE